### ISSUE TITLE
class vs interface

### ISSUE THREAD

**Issue by vlad-yaremenko** [andrhome/Maxtvmedia_angular2_GitHub#3]
https://github.com/andrhome/Maxtvmedia_angular2_GitHub/blob/master/src/views/parsels-view/post-services/post-service.ts#L1-L5

Нужно заменить на `interface` ибо `class` не предназначен для шаблона. В `class` нужно инициализировать все поля и методы. `interface` это просто шаблон который говорит какие свойства есть.

**Comment by andrhome** [comment]
Changed
